### PR TITLE
Delete request

### PR DESCRIPTION
**Pull request by ss-deep**
-I’ve added a temporary delete request button to the table. It will be relocated to a different spot once we finalize its position.
- Asks for confirmation before deleting the request
- Request can be delete by user who created it and if its not active.

I accidentally pushed additional changes to the same branch. Here’s an overview of the updates made:

- Replaced Axios with Fetch for API calls.
- Implemented functionality for completing requests: Beekeepers can now cancel or mark requests as completed.
- Updated table status:
- Changed from 'Active' and 'Inactive' to 'Pending' when a request is accepted and 'Completed' when fulfilled.
- Added functionality to allow the request creator to delete a completed request.
- Modified modal buttons to toggle based on the current operation.

I apologize if the code isn’t as modular or well-formatted as it could be; I’m still learning how to refactor code into components. Any suggestions for improvement would be appreciated! :)

image

image

### CODE REVIEW

**Review by r1g023 — APPROVED** [review]
Nice job @ss-deep - I tried running it locally and it works as intended.

**Comment by ss-deep** [comment]
> Nice job @ss-deep - I tried running it locally and it works as intended.

Thanks @r1g023 for testing it! Please check the updated code as well, when you have time :)

**Review by NishaVijai — APPROVED** [review]
Looks like an important update :-) Thank you @ss-deep

**Comment by KseniiaRiabova** [comment]
@ss-deep Don't worry about it! If the code is doing what it’s supposed to do, that's already a win. Refactoring can always come later once everything’s functioning smoothly. Keep learning and improving at your own pace—you're doing great! 🚀

I have a question. If the user created a request, the request is aActive:true, the user wants to delete this request then the user should first accept it get isActive:false and then delete it? or accept it and then click isCompleted:true. 

Or we don't specify for an author isActive:false, and allow user delete at every step no matter isActive:true or isActive:false. 

Which approach for us is more efficient in your opinion?

**Review by KseniiaRiabova — APPROVED** [review]

**Review by Valeriusdev — APPROVED** [review]

**Pull request merged**
