### PR TITLE
Implement request CRUD operations with validation and API overview do…

### PR DESCRIPTION
**Pull request by KseniiaRiabova**
# Files Updated:

### File: requestController.js
**Changes:**
- Create Request: Validates request body, verifies user existence, and saves new request. Responds with success or failure.
- Update Request: Validates request body, verifies user permissions, updates request, and responds with status.
- Delete Request: Verifies user permissions, deletes request, and responds with status.
- Accept Request: Verifies request's active status, updates acceptance details, and responds with status.
- Cancel Accepted Request: Verifies user's accepted request, updates cancellation details, and responds with status.
- Complete Request: Verifies request's acceptance and user involvement, updates completion details, and responds with status.
- List All Requests: Retrieves all requests with populated user details, and responds with status.

### File: requestValidator.js
**Changes:**
- Added Joi validation schema for request fields, including title, description, image, contact number, status flags, timestamps, user IDs, and location. Custom error messages for invalid fields.

### File: requestRoutes.js
**Changes:**
- Defined routes for creating, updating, deleting, accepting, canceling, completing, and listing requests. Applied JWT authentication middleware to protect endpoints.

### File: README.md
**Changes:**
- Added a link to the detailed API overview documentation located in docs/api-overview.md.

### Files: userController.js, DashboardController.js
**Changes:**
- Improved user safety by ensuring user IDs are derived from authentication tokens.

### Models Updated:
- User and Request models to reflect new validation requirements.

### Testing:
- Fully tested all endpoints using Postman to ensure correct functionality.

### CODE REVIEW

**Review by r1g023 — APPROVED** [review]
Nice job, @KseniiaRiabova! This PR is very informative and detailed. I love it!

**Comment by KseniiaRiabova** [comment]
> Nice job, @KseniiaRiabova! This PR is very informative and detailed. I love it!

I am learning from you! Thank you @r1g023

**Review by NishaVijai — APPROVED** [review]
Thank you for the excellent work @KseniiaRiabova  :-)

**Review by sharafcs50 — APPROVED** [review]

**Review by Valeriusdev — APPROVED** [review]

**Review by PongRVA — APPROVED** [review]
Excellent job, @KseniiaRiabova !!

**Pull request merged**
