### PR TITLE
BEE-84: Update Chart Component - Enhance Font and Interactivity

### PR DESCRIPTION
**Pull request by Natkuma01**
### Description
The following updates have been made to the chart component:
1. Font Updates:
    - Updated the chart title and axis labels (X and Y) to use the "Blinker" font, which is consistent with the rest of the application.
    - Changed the font color to black.
    - Increased the font size of the X-axis (Years) and Y-axis (Millions of Hives) labels for better visibility.

2. Chart Interactivity:
    - Made the entire chart clickable.
    - Implemented notification using to alert users when they are about to navigate to the official website.

### Changes Made
- Added `blinker: ["blinkerBold]` in tailwind.config.js. 
- Added font-weight and changed text color for the title
- Installed React-toastify to show a notification before redirecting users to an external website.

### How to Test
1. Navigate to the chart component in the application.
2. Verify that the chart title and axis labels now use the "Blinker" font and appear in black.
3. Check that the X and Y axis labels have increased in size.
4. Click on the chart and ensure that a notification window appears on the top left corner, warning the user before redirecting to the official website.
5. Wait for the window closed and direct to the official website in a new window.

### Dependencies
- React-toastify: Added to display notifications to the user.

### Linked Issue
[Jira Issue BEE-84](https://kseniiariabova.atlassian.net/jira/software/projects/BEE/boards/6?atlOrigin=eyJwIjoiaiIsImkiOiIyYThmMjc5OWY1ZjI0NjlmOWQxN2E0YTk1NWQzZDc2MyJ9&cloudId=f3112682-dc3c-4cce-a8da-0c6e8caab403&selectedIssue=BEE-84)

### Screenshot
Screenshot 2024-09-18 at 12 52 58 PM

### CODE REVIEW

**Comment by KseniiaRiabova** [comment]
Amazing job, amazing PR, everything is working properly @Natkuma01

**Review by KseniiaRiabova — APPROVED** [review]

**Review by ss-deep — APPROVED** [review]
It looks great @Natkuma01

**Review by eatwanderexplore — APPROVED** [review]

**Review by r1g023 — APPROVED** [review]
Such a clean PR! Love the Toastify popup, it gives the UI a much cleaner look @Natkuma01

**Review by NishaVijai — APPROVED** [review]
Amazing work @Natkuma01 :-) It is interesting to learn the toaster implementation from your code. Thank you.

**Review by Valeriusdev — APPROVED** [review]

**Pull request merged**
