### PR TITLE
add request modal when clicking on the 'details' button

### PR DESCRIPTION
**Pull request by r1g023**
# UPDATES
- Created a request modal (`AcceptRequestModal.jsx`) for the 'Details' button, which opens a Request Details modal upon click.
- Integrated the modal within the `RequestTable.jsx` component.
- Modified the `RequestTable.jsx` component to toggle the edit button when the 'Details' button is clicked.
- Added a white text color effect to the 'Details' and 'Cancel' buttons on hover for a cleaner look.
- As per Jira issue 73 ([link](https://kseniiariabova.atlassian.net/jira/software/projects/BEE/boards/6?selectedIssue=BEE-73)), the modal is designed to display details and information for the selected city.

# QA
- It may be beneficial to refactor the columns object in the `RequestTable.jsx` component, moving it to a different location for improved readability later. 
- Focused on functionality; the modal could be further enhanced for responsiveness in the future.

# Attachments
- Please see the attached files and feel free to provide feedback.
requestDetails

### CODE REVIEW

**Comment by eatwanderexplore** [comment]
I think the modal looks good. It stays on top for the most part, but I did notice that it goes under the map when I scroll down.
Screenshot 2024-09-25 at 11 51 38 AM

**Comment by r1g023** [comment]
> I think the modal looks good. It stays on top for the most part, but I did notice that it goes under the map when I scroll down. Screenshot 2024-09-25 at 11 51 38 AM

Hi Jenny,

Thanks for the feedback! That map issue has been around for a while. Since I've been focused on the Modal task for my current Jira ticket, I think it might make sense to create a separate task to address the map overlapping the Modal and other elements in the app, it could be due to its z-index being higher than the others. I'm not sure if anyone is already working on it, and I usually avoid addressing issues outside of my assigned task to prevent duplicates. Great catch, though! I'll inform our Scrum Master and PO here.

@Valeriusdev @KseniiaRiabova , is there an existing Jira ticket for fixing this map issue? If not, I’d be happy to create one. Also, @eatwanderexplore  could take a look and resolve the overlapping problem. Thoughts?

**Comment by KseniiaRiabova** [comment]
> > I think the modal looks good. It stays on top for the most part, but I did notice that it goes under the map when I scroll down. Screenshot 2024-09-25 at 11 51 38 AM
> 
> Hi Jenny,
> 
> Thanks for the feedback! That map issue has been around for a while. Since I've been focused on the Modal task for my current Jira ticket, I think it might make sense to create a separate task to address the map overlapping the Modal and other elements in the app, it could be due to its z-index being higher than the others. I'm not sure if anyone is already working on it, and I usually avoid addressing issues outside of my assigned task to prevent duplicates. Great catch, though! I'll inform our Scrum Master and PO here.
> 
> @Valeriusdev @KseniiaRiabova , is there an existing Jira ticket for fixing this map issue? If not, I’d be happy to create one. Also, @eatwanderexplore could take a look and resolve the overlapping problem. Thoughts?

@r1g023 @eatwanderexplore good you pointed out this issue, I believe @Valeriusdev have reached @r1g023 about this subject

**Comment by KseniiaRiabova** [comment]
Additionally, what a good PR @r1g023! as always. I will review today and approve

**Review by KseniiaRiabova — APPROVED** [review]
Good Job!

**Review by ss-deep — APPROVED** [review]
It looks great @r1g023 !

**Comment by r1g023** [comment]
Thanks to @ss-deep  for noticing that I wasn’t accurately retrieving the latitude and longitude from the database. I hadn’t checked the API reference or server, so I missed that the data was nested under 'coordinates' instead of 'lat'. After updating it, the coordinates are now correctly retrieved for each clicked item. I also removed the 'N/A' sections since coordinates are required, making "N/A" unnecessary. Apologies for overlooking this earlier, I've repushed my changes, and it should be correct now.

updateLongLat

**Review by eatwanderexplore — APPROVED** [review]
@r1g023 Thank you for explaining!

**Review by Valeriusdev — APPROVED** [review]

**Pull request merged**
