### PR TITLE
added footer folder containing footer components

### PR DESCRIPTION
**Pull request by r1g023**
### Footer Updates:

- Created a Footer folder within the Components directory to improve readability and organization.
- Implemented design based on Sharaf's Figma file.
- Added additional colors to the `tailwind.config.js` file.
- Ensured responsiveness across various devices is functioning as expected.
- Please let me know if any further updates are needed; I'm happy to make adjustments.

## SEE ATTACHED 
mobileView

desktopView

### CODE REVIEW

**Comment by r1g023** [comment]
Hold, I forgot to pull any new updates changes before pushing to my branch so there were merge conflicts, I'll fix today.

**Comment by NishaVijai** [comment]
@r1g023 Please fetch the changes from "development" branch from today :-) Ksusha have fixed/updated the conflicts (the same files) from her branch today and the updated changes got merged on development branch few minutes ago. Even after fetching the changes, if you see conflicts, it will be mostly with the imports & new dependencies (on package.json file). Please let me know, if you need help resolving conflicts.

**Comment by r1g023** [comment]
> @r1g023 Please fetch the changes from "development" branch from today :-) Ksusha have fixed/updated the conflicts (the same files) from her branch today and the updated changes got merged on development branch few minutes ago. Even after fetching the changes, if you see conflicts, it will be mostly with the imports & new dependencies (on package.json file). Please let me know, if you need help resolving conflicts.

All set. I pulled from the Dev branch and resolved the merge conflicts. It is working now, and I was able to add the new changes to my previous work. Please review and let me know if you have any questions.

**Comment by KseniiaRiabova** [comment]
@r1g023 your PRs are always great, thank you for providing us with information and screenshots!

**Review by KseniiaRiabova — APPROVED** [review]

**Comment by PongRVA** [comment]
Nice job @r1g023!  Looks great!

**Review by PongRVA — APPROVED** [review]
Nice job @r1g023. Looks great!

**Review by sharafcs50 — APPROVED** [review]
Approved

**Pull request merged**
