### PR TITLE
Created a New Request form 

### PR DESCRIPTION
**Pull request by ss-deep**
Implemented a request form for users to create new requests.

- When the user clicks the "Send New Request" button, it opens a modal with the request form. The form includes fields for title, description, location (coordinates, city, and country), contact number, and image.

- Validations are applied to all input fields, and error messages are provided by the backend Joi library. When validation fails, an error message is displayed to the user within the form.

- After successful validation, a POST request is sent to the api/requests endpoint.

- The form also shows the previous contact number of the user if exists.

### CODE REVIEW

**Review by r1g023 — APPROVED** [review]

**Review by Valeriusdev — APPROVED** [review]

**Review by NishaVijai — APPROVED** [review]
Awesome update :-) & thank you for the wonderful work @ss-deep

**Review by Valeriusdev — CHANGES_REQUESTED** [review]
@ss-deep, when you have some free time, could you please resolve a merge conflict?

**Comment by ss-deep** [comment]
i have resolved the merge conflicts. :)

**Review by KseniiaRiabova — APPROVED** [review]
Thank you!

**Review by KseniiaRiabova — APPROVED** [review]

**Review by Valeriusdev — APPROVED** [review]

**Pull request merged**
