### PR TITLE
Main

### PR DESCRIPTION
**Pull request by eatwanderexplore**
added variables to manage local vs deployed state when calling the api from the BE to the FE.

### CODE REVIEW

**Review by r1g023 — APPROVED** [review]
Nice job @eatwanderexplore 

There are a few conflicts with the branch, but otherwise, it looks fantastic!

**Review by NishaVijai — APPROVED** [review]
@eatwanderexplore Thank you for the nice update :-) I got confused with the message "Main".

**Review by ss-deep — APPROVED** [review]
@eatwanderexplore nice job!

**Review by Valeriusdev — APPROVED** [review]

**Review by Natkuma01 — APPROVED** [review]

**Review by KseniiaRiabova — APPROVED** [review]
Great job @eatwanderexplore

**Pull request merged**
