### PR TITLE
Add redux toolkit logic to pass user data from BE to FE using store

### PR DESCRIPTION
**Pull request by NishaVijai**
This PR file changes are necessary to proceed our voyage on V51 :-) It can be merged on development and then on main (if it is the right flow to merge on main V50 repo). You can approve this PR, when you have time. I guess, @KseniiaRiabova will create a V51 main branch from our V50 main branch.

### CODE REVIEW

**Review by Natkuma01 — APPROVED** [review]

**Review by KseniiaRiabova — APPROVED** [review]
@NishaVijai Thank you for your great job and dedication

**Review by ss-deep — APPROVED** [review]
Great work! Thank you @NishaVijai !

**Review by eatwanderexplore — APPROVED** [review]
Great work, @NishaVijai . I learned about how configureStore sets up combineReducers implicitly from reviewing your code. Thanks!

**Review by r1g023 — APPROVED** [review]
Nice job Nisha, you're a rockstar!

**Review by Valeriusdev — APPROVED** [review]

**Pull request merged**
