### PR TITLE
Update / accordion menu

### PR DESCRIPTION
**Pull request by Valeriusdev**

### CODE REVIEW

**Review by NishaVijai — APPROVED** [review]
Great work. Thank you @Valeriusdev :-)

**Comment by KseniiaRiabova** [comment]
Good job @Valeriusdev!

**Review by KseniiaRiabova — APPROVED** [review]

**Review by r1g023 — APPROVED** [review]
nice job Val

**Review by ss-deep — APPROVED** [review]
Good job @Valeriusdev !

**Comment by r1g023** [comment]
Per Val, merge PR

**Pull request merged**
