### PR TITLE
Add profile modal to footer and GitHub logo hover effect

### PR DESCRIPTION
**Pull request by r1g023**
## New Footer Updates

- Implemented a notification popup for GitHub and LinkedIn links, warning users before navigating away, as per [Jira ticket BEE-51](https://kseniiariabova.atlassian.net/jira/software/projects/BEE/boards/6?selectedIssue=BEE-51).
- Integrated @PongRVA  `ModalResourceLink.jsx` for this feature, thanks, Andy!
- Added a black background hover effect on the GitHub logo.

### QA

- When the notification popup appears, the map in the middle does not have opacity applied, causing it to appear without the intended effect. This issue might be related to a z-index problem and could be addressed in a future task, thoughts? 

### See attached:
mapfeature

update_footer_notification

### CODE REVIEW

**Review by sharafcs50 — APPROVED** [review]

**Review by Valeriusdev — APPROVED** [review]

**Review by NishaVijai — CHANGES_REQUESTED** [review]
Thank you for the wonderful work @r1g023 :-) Can you please fetch/pull changes from development and make a new PR?

**Comment by r1g023** [comment]
> Thank you for the wonderful work @r1g023 :-) Can you please fetch/pull changes from development and make a new PR?

Hi @NishaVijai thanks for the update. Instead of creating a new branch, I checked out the Dev branch, pulled the latest changes, and rebased to apply your updates to my existing branch. Everything is now working as expected, including the updated UI menu. Please review and let me know if you have any questions.

@KseniiaRiabova - Please review as well if you have a moment. 

UPDATE: I didn't realize you mentioned creating a new PR, not a new branch. Sorry for misreading that. Either way, I followed the steps you outlined.

**Review by NishaVijai — APPROVED** [review]

**Review by NishaVijai — APPROVED** [review]
Thank you @r1g023 changes looks great :-)

**Review by ss-deep — APPROVED** [review]
looks nice, thank you @r1g023 !

**Review by Valeriusdev — CHANGES_REQUESTED** [review]
@r1g023, could you please resolve a merge conflict?

**Review by KseniiaRiabova — APPROVED** [review]

**Review by Valeriusdev — APPROVED** [review]

**Pull request merged**
