### PR TITLE
Add signup form and move layout component

### PR DESCRIPTION
**Pull request by NishaVijai**

### CODE REVIEW

**Review by Valeriusdev — CHANGES_REQUESTED** [review]
@NishaVijai, could you please resolve this merge conflict that appeared after merging the previous PR?

**Comment by NishaVijai** [comment]
@Valeriusdev conflict must be because of I moved and renamed Layout.jsx to HomeLayout.jsx. Where can I resolve it? Will you guide me how I can fix it.

**Comment by NishaVijai** [comment]
Hello @Valeriusdev I have resolved the conflict and pushed the changes. I will also make a new PR, since I misunderstood Ksusha's requirement.

**Comment by NishaVijai** [comment]
I will close this PR with this comment. Will make a new PR with updated changes.

**Pull request closed without merging**
