### PR TITLE
added Modal for details button on request table, including edit and c…

### PR DESCRIPTION
**Pull request by r1g023**
## Overview
- Updated the `AcceptRequestModal.jsx` component to integrate logic from the backend.
- When a user clicks 'accept', they are converted into a beekeeper.
- After accepting the request, the beekeeper can cancel it but cannot edit the request.
- The same logic applies to a beefinder who creates a request: they can edit or cancel the request if it's no longer needed. Also, the beefinder (request creator) can 'accept' their own request. Further clarification on this might be needed from @KseniiaRiabova 
- Added a new `AcceptRequestCall.jsx` component that handles sending requests to the server for accepting the request.

## QA
- I’m aware that @ss-deep has refactored much of the `RequestTable.jsx` code, organizing it into separate sections. I plan to pull her changes and merge them with mine, which might require further edits on my end.
- Everything seems to be functioning correctly for now. The 'accept' button works as intended, converting the logged-in user to a 'beekeeper' when a request is accepted. However, the 'edit' and 'cancel' buttons still need functionality. I believe Deepali also worked on the 'edit' feature, so I may need to incorporate her code.
- The request table doesn’t refresh when new data is added. It might be worth considering adding a subscription or a real-time library to enable posts to refresh without reloading the page, just a thought.

## Screenshots

- **Beekeeper Accepting Request**: A beekeeper who accepts the request can also cancel it if they change their mind.
  BeeKeeperAcceptRequest

- **Accepted Request View**: Registered users viewing a request will see when it’s accepted by someone else, hence no 'cancel' button appears on the modal.
  BeeKeeperOtherUserAccepted

- **Beefinder Managing Request**: The beefinder (request creator) can accept, edit, or cancel the request.
  BeeFinderRequest

### CODE REVIEW

**Comment by r1g023** [comment]
Will create a second commit to merge @ss-deep 's code into my branch and will resolve conflict right after

**Comment by r1g023** [comment]
@ss-deep @KseniiaRiabova @Valeriusdev 
i have fixed merged conflicts and went ahead and merged Deepali's code into mine, had to update a few sections of the column component for it to match what I had before the merge, it's all working fine. In case you all want to review and approve so that Deepali can work on her next task, please.

**Review by NishaVijai — APPROVED** [review]
@r1g023 Awesome work. Thank you so much for your time and effort :-) There were some unresolved conflicts yesterday, but you have resolved it now. Thank you.

**Review by KseniiaRiabova — APPROVED** [review]
@r1g023 and @ss-deep thank you for your great work and efficient collaboration!

**Review by Valeriusdev — APPROVED** [review]

**Pull request merged**
