### PR TITLE
Test dark-light-mode-setup branch

### PR DESCRIPTION
**Pull request by NishaVijai**
Add text color - white in dark mode

### CODE REVIEW

**Comment by NishaVijai** [comment]
Team, I have accidentally pushed my actual setup with this light/dark mode. This PR is to test my branch in order to proceed with the implementation. Sorry for the mistake :-)

**Review by KseniiaRiabova — APPROVED** [review]
Thank you @NishaVijai

**Comment by r1g023** [comment]
> Team, I have accidentally pushed my actual setup with this light/dark mode. This PR is to test my branch in order to proceed with the implementation. Sorry for the mistake :-)

Thanks for confirming that. Just to clarify, this PR shouldn't be merged at all, correct? It does look cool when you toggle the dark mode on, though.

**Comment by NishaVijai** [comment]
> > Team, I have accidentally pushed my actual setup with this light/dark mode. This PR is to test my branch in order to proceed with the implementation. Sorry for the mistake :-)
> 
> Thanks for confirming that. Just to clarify, this PR shouldn't be merged at all, correct? It does look cool when you toggle the dark mode on, though.

**Comment by NishaVijai** [comment]
@r1g023 I have to implement Figma design (add toggle button on navbar) and apply the changes on entire webpage. We can wait on merging this branch :) Thank you for asking about merging. I will write, if this PR is ready to merge on development.

**Review by r1g023 — CHANGES_REQUESTED** [review]
Per @NishaVijai 
_I have to implement Figma design (add toggle button on navbar) and apply the changes on entire webpage. We can wait on merging this branch :) Thank you for asking about merging. I will write, if this PR is ready to merge on development._

**Comment by r1g023** [comment]
> @r1g023 I have to implement Figma design (add toggle button on navbar) and apply the changes on entire webpage. We can wait on merging this branch :) Thank you for asking about merging. I will write, if this PR is ready to merge on development.

Thanks for the information. In the meantime, I've submitted the PR with your note that further changes are needed before merging to avoid confusion.

**Review by sharafcs50 — APPROVED** [review]

**Review by Valeriusdev — APPROVED** [review]

**Pull request merged**
