### PR TITLE
Add user profile and update dashboard

### PR DESCRIPTION
**Pull request by NishaVijai**
Add user profile initial setup and update dashboard component. This PR can be merged into development after 5 reviews and @KseniiaRiabova  agrees to the update I made :-)

### CODE REVIEW

**Review by r1g023 — APPROVED** [review]
Nice job @NishaVijai

**Review by ss-deep — APPROVED** [review]

**Review by ss-deep — APPROVED** [review]
awesome job! thank you @NishaVijai !

**Review by Valeriusdev — CHANGES_REQUESTED** [review]
@NishaVijai, I'm wondering why this PR isn't deploying?

**Comment by NishaVijai** [comment]
@Valeriusdev I don't know why. FE changes were something like, I added components as I used to do in my previous PR's. In this PR, I have to modify "Dashboard.jsx" component (@KseniiaRiabova created this earlier). I am not sure, if my changes on this Dashoboard.jsx component is causing trouble. If you can branch in inside my working branch, the flow is working fine.

**Review by Valeriusdev — APPROVED** [review]
Good job!

**Review by KseniiaRiabova — APPROVED** [review]

**Review by sharafcs50 — APPROVED** [review]

**Comment by KseniiaRiabova** [comment]
Perfect, @NishaVijai, thank you

**Pull request merged**
