### PR TITLE
added navbar and footer to solutions page

### PR DESCRIPTION
**Pull request by eatwanderexplore**
I placed the Solutions container from the home page as a placeholder temporarily. I think we eventually want to add the solutionData to the page. But the navbar and footer have been added.

### CODE REVIEW

**Review by ss-deep — APPROVED** [review]
great job @eatwanderexplore !

**Review by KseniiaRiabova — APPROVED** [review]
Great work @eatwanderexplore

**Review by NishaVijai — APPROVED** [review]
Thank you @eatwanderexplore for the update :-)

**Review by r1g023 — APPROVED** [review]
Great job @eatwanderexplore

**Comment by KseniiaRiabova** [comment]
I love your great initiative in adding the temporary container to the page!

**Review by Valeriusdev — APPROVED** [review]

**Pull request merged**
