### PR TITLE
Add responsive design, light/dark mode, set max-width and burger menu

### PR DESCRIPTION
**Pull request by NishaVijai**
Add responsive design, light/dark mode, set max-width for larger screens and burger menu. Update existing components to adapt light/dark theme & modify components with reusable components. Design needs some more improvement. This design is not a final version. After PR reviews, these changes can be merged into development. Thank you :-)

### CODE REVIEW

**Review by r1g023 — APPROVED** [review]
Nice job Nisha, I love the new menu and UI

**Review by sharafcs50 — APPROVED** [review]

**Comment by NishaVijai** [comment]
solving the merge conflict. Package-lock.json changes are causing some trouble. I will finish it soon. 185 lines of conflicts on package-lock.json. It took some time to solve that. Please do fetch the changes, once this branch is merged into development . if possible, delete package-lock.json from client folder & then run npm i. Hope, all dependencies works fine.

**Review by Valeriusdev — APPROVED** [review]

**Review by ss-deep — APPROVED** [review]
light and dark mode is working nice! Great job @NishaVijai

**Review by Valeriusdev — CHANGES_REQUESTED** [review]
@NishaVijai, when you have some free time, could you please resolve a merge conflict?

**Comment by NishaVijai** [comment]
I have updated components (for this PR to work properly) after solving merge conflicts. This PR can be merged into development. @r1g023 please do check my changes from this PR & if you would like to use your burgermenu implementation, you can look into Header.jsx and Nav.jsx files and make the changes, changes you did 3 days ago, I guess :-)

**Review by Valeriusdev — APPROVED** [review]

**Pull request merged**
