### PR TITLE
add Map component

### PR DESCRIPTION
**Pull request by Valeriusdev**

### CODE REVIEW

**Review by NishaVijai — APPROVED** [review]
Amazing work @Valeriusdev :-) React-Leaflet is new to me. Happy to learn it from your implementation.

**Review by KseniiaRiabova — APPROVED** [review]
@Valeriusdev What a great job!

**Review by r1g023 — APPROVED** [review]
Nice job, everything looks nice

**Review by PongRVA — APPROVED** [review]
Looks great!

**Pull request merged**
