### PR TITLE
Bugfix/map overlapping elements

### PR DESCRIPTION
**Pull request by r1g023**
## UPDATES
- Resolved the issue of the map overlapping the modal when opening it to create a request.
- Updated the `AcceptRequestCall.jsx` component to utilize the Fetch API instead of Axios, per @NishaVijai  and @KseniiaRiabova  feedback.

## QA
- Consider refactoring the entire request structure of the app if future features are implemented.

## ATTACHMENTS
fixMapOverlapIssue

### CODE REVIEW

**Comment by r1g023** [comment]
I may have accidentally continued working on Jenn's branch while testing the stack logo placement for feedback. As a result, my committed PR ended up on her branch instead of DEV (pull/fetch), combining her changes with mine. Since her PR hasn’t been merged yet, you can find Jenn's PR here: [PR #147](https://github.com/chingu-voyages/v50-tier3-team-28/pull/147). This means my PR may include both sets of changes. I think I forgot to check out the DEV branch to fetch first before making my commits. Please let me know if it's okay to merge as is, or if I should redo the git commit using the DEV branch instead.

**Review by NishaVijai — APPROVED** [review]
Wonderful update @r1g023 :-) Thank you.

**Comment by KseniiaRiabova** [comment]
> I may have accidentally continued working on Jenn's branch while testing the stack logo placement for feedback. As a result, my committed PR ended up on her branch instead of DEV (pull/fetch), combining her changes with mine. Since her PR hasn’t been merged yet, you can find Jenn's PR here: [PR #147](https://github.com/chingu-voyages/v50-tier3-team-28/pull/147). This means my PR may include both sets of changes. I think I forgot to check out the DEV branch to fetch first before making my commits. Please let me know if it's okay to merge as is, or if I should redo the git commit using the DEV branch instead.

@r1g023 can you make the tailwind icon as beautiful as it was before?

**Review by KseniiaRiabova — CHANGES_REQUESTED** [review]
Tailwind Icon

**Review by ss-deep — APPROVED** [review]
Great job @r1g023

**Comment by r1g023** [comment]
@KseniiaRiabova 

Since Jenn's PR has been merged, her commits have been added to the Dev branch. I made sure to pull all changes from the Dev branch, so the only fix I applied to my branch is the Tailwind CSS logo (besides Fetch and Map overlap issue). Please find the updated logo attached.

fixedTailwindLogo

**Comment by KseniiaRiabova** [comment]
@r1g023 thank you a lot for this fast update. Great job!!!

**Review by KseniiaRiabova — APPROVED** [review]

**Review by Valeriusdev — APPROVED** [review]

**Pull request merged**
